### ISSUE TITLE
Create a function which makes a plot showing number of cell types associated with phenotypes that are descendants of a particular HPO term

### ISSUE THREAD

**Issue by NathanSkene** [neurogenomics/MultiEWCE#4]
E.g. to enable you to make https://github.com/neurogenomics/rare_disease_ewce/issues/2

**Comment by bschilder** [comment]
I've made a new function to do this aggregation both ways:

## Count phenotypes grouped by celltypes

```R
plt1 <- MultiEWCE::summary_plot(count_var = "Phenotype", group_var = "CellType")
```
![Screenshot 2023-01-20 at 15 54 10](https://user-images.githubusercontent.com/34280215/213744994-26481767-191d-4819-b2dc-b6a7c323cf36.png)


## Count celltypes grouped by phenotypes

```R
plt2 <- MultiEWCE::summary_plot(count_var = "CellType", group_var = "Phenotype")
```
![Screenshot 2023-01-20 at 16 00 05](https://user-images.githubusercontent.com/34280215/213745799-7c22915c-c8b6-4d8e-9d73-f3b2877e21af.png)


Since there's thousands of significant phenotypes, I've added some additional filtering args so users can easily subset by some common ancestor in the ontology:

![Screenshot 2023-01-20 at 16 02 11](https://user-images.githubusercontent.com/34280215/213746093-efca82f6-3f74-4a21-94b0-da8151e0de48.png)
